version: '3.4'

services:
  simpleprojectloggerserver:
    image: ${DOCKER_REGISTRY-}simpleprojectloggerserver
    build:
      context: .
      dockerfile: SimpleProjectLoggerServer/Dockerfile
    ports:
      - "80:80" 
    networks:
      - app-network
  pdb:
    image: postgres:12.3-alpine
    container_name: spl-pdb
    restart: unless-stopped
    tty: true
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=${DB_DATABASE}
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    networks:
      - app-network
networks:
  app-network:
    driver: bridge
volumes:
  pgdata:
    driver: local